### ISSUE TITLE
Which one is correct?

### ISSUE THREAD

**Issue by pengzhile** [JetBrains/marketplace-makemecoffee-plugin#2]
**Case 1:**
[jetbrains plugin docs](https://plugins.jetbrains.com/docs/marketplace/add-marketplace-license-verification-calls-to-the-plugin-code.html)
<img width="752" alt="image" src="https://user-images.githubusercontent.com/343491/76203952-74760580-6232-11ea-8605-15af64f92156.png">

**Case 2:**
[demo plugin src](https://github.com/JetBrains/marketplace-makemecoffee-plugin/blob/master/src/main/java/license/CheckLicense.java#L172)
<img width="790" alt="image" src="https://user-images.githubusercontent.com/343491/76204031-97081e80-6232-11ea-8c8f-5dffb7420b6a.png">

So, which is the correct one?

**Comment by LChernigovskaya** [comment]
@pengzhile the first one from docs is correct. Sorry for misleading
